package edu.uclm.esi.videochat;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.RemoteWebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.annotation.Order;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoAlertPresentException;
import org.openqa.selenium.Point;

import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

import edu.uclm.esi.videochat.springdao.UserRepository;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class RegistrarLoginTest {
	private WebDriver chrome;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Autowired
	UserRepository usersRepo;

	@Before
	public void setUp() {
		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		
		options.addArguments("--use-fake-device-for-media-stream");
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\CLASE\\Desktop\\TSW\\chromedriver.exe");

		chrome = new ChromeDriver(options);
		js = (JavascriptExecutor) chrome;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		//chrome.quit();
	}

	@Test
	@Order(1)
	public void registrarLoginPepe() {

		usersRepo.delete(usersRepo.findByName("PepeSelenium"));
		chrome.get("https://localhost:7500/?ojr=register");

		chrome.findElement(By.id("details-button")).click();
		chrome.findElement(By.id("proceed-link")).click();
		chrome.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("PepeSelenium");
		cajaEmail.sendKeys("PepeSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chrome.findElement(By.id("btnCrearCuenta"));

		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.switchTo().alert().accept();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();
		
		loginNombre.sendKeys("PepeSelenium");
		loginPwd.sendKeys("123");
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		btnEntrar.click();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
	}
	
	@Test
	@Order(2)
	public void registrarLoginAna() {

		usersRepo.delete(usersRepo.findByName("AnaSelenium"));
		chrome.get("https://localhost:7500/?ojr=register");

		chrome.findElement(By.id("details-button")).click();
		chrome.findElement(By.id("proceed-link")).click();
		chrome.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("AnaSelenium");
		cajaEmail.sendKeys("AnaSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chrome.findElement(By.id("btnCrearCuenta"));

		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.switchTo().alert().accept();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();
		
		loginNombre.sendKeys("AnaSelenium");
		loginPwd.sendKeys("123");
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		btnEntrar.click();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));

	}

	
	@Test
	@Order(3)
	public void registrarLoginLucas() {

		usersRepo.delete(usersRepo.findByName("LucasSelenium"));
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.get("https://localhost:7500/?ojr=register");

		chrome.findElement(By.id("details-button")).click();
		chrome.findElement(By.id("proceed-link")).click();
		chrome.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chrome
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("LucasSelenium");
		cajaEmail.sendKeys("LucasSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chrome.findElement(By.id("btnCrearCuenta"));

		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.switchTo().alert().accept();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chrome.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();
		
		loginNombre.sendKeys("LucasSelenium");
		loginPwd.sendKeys("123");
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		//chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button")).click();
		btnEntrar.click();
		chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
	}

	
}