package edu.uclm.esi.videochat;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.RemoteWebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.annotation.Order;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoAlertPresentException;
import org.openqa.selenium.Point;

import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

import edu.uclm.esi.videochat.springdao.UserRepository;
import junit.framework.Assert;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class RegistrarLoginTest {
	private WebDriver chromeAna;
	private WebDriver chromeLucas;
	private WebDriver chromePepe;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Autowired
	UserRepository usersRepo;

	@Before
	public void setUp() {
		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\CLASE\\Desktop\\TSW\\chromedriver.exe");

		// chrome = new ChromeDriver(options);

		// js = (JavascriptExecutor) chrome;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		// chrome.quit();
	}

	@Test
	@Order(1)
	public void registrarLoginPepe() {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");

		chromePepe = new ChromeDriver(options);

		usersRepo.delete(usersRepo.findByName("PepeSelenium"));
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromePepe.get("https://localhost:7500/?ojr=register");

		chromePepe.findElement(By.id("details-button")).click();
		chromePepe.findElement(By.id("proceed-link")).click();
		chromePepe.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("PepeSelenium");
		cajaEmail.sendKeys("PepeSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		chromePepe.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chromePepe.findElement(By.id("btnCrearCuenta"));

		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chromePepe.switchTo().alert().getText(), is("Registrado correctamente"));
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromePepe.switchTo().alert().accept();
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("PepeSelenium");
		loginPwd.sendKeys("123");
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		btnEntrar.click();
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement titulo = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
		// Assert.assertEquals(ActualTitle, ExpectedTitle)
		assertThat(titulo.getText(), is("Fantastico videochat"));

	}

	@Test
	@Order(2)
	public void registrarLoginAna() {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");

		chromeAna = new ChromeDriver(options);

		usersRepo.delete(usersRepo.findByName("AnaSelenium"));
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeAna.get("https://localhost:7500/?ojr=register");

		chromeAna.findElement(By.id("details-button")).click();
		chromeAna.findElement(By.id("proceed-link")).click();
		chromeAna.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("AnaSelenium");
		cajaEmail.sendKeys("AnaSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		chromeAna.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chromeAna.findElement(By.id("btnCrearCuenta"));

		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chromeAna.switchTo().alert().getText(), is("Registrado correctamente"));
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeAna.switchTo().alert().accept();
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("AnaSelenium");
		loginPwd.sendKeys("123");
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		btnEntrar.click();
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement titulo = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
		// Assert.assertEquals(ActualTitle, ExpectedTitle)
		assertThat(titulo.getText(), is("Fantastico videochat"));

	}

	@Test
	@Order(3)
	public void registrarLoginLucas() {
		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");
		chromeLucas = new ChromeDriver(options);
		usersRepo.delete(usersRepo.findByName("LucasSelenium"));
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeLucas.get("https://localhost:7500/?ojr=register");

		chromeLucas.findElement(By.id("details-button")).click();
		chromeLucas.findElement(By.id("proceed-link")).click();
		chromeLucas.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));

		cajaNombre.sendKeys("LucasSelenium");
		cajaEmail.sendKeys("LucasSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeLucas.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button")).click();
		WebElement botonCrearCuenta = chromeLucas.findElement(By.id("btnCrearCuenta"));

		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		assertThat(chromeLucas.switchTo().alert().getText(), is("Registrado correctamente"));
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeLucas.switchTo().alert().accept();
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement loginNombre = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("LucasSelenium");
		loginPwd.sendKeys("123");
		// chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		// chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button")).click();
		btnEntrar.click();
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement titulo = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
		// Assert.assertEquals(ActualTitle, ExpectedTitle)
		assertThat(titulo.getText(), is("Fantastico videochat"));
	}

}