package edu.uclm.esi.videochat;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.RemoteWebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.annotation.Order;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NoAlertPresentException;
import org.openqa.selenium.Point;

import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

import edu.uclm.esi.videochat.springdao.UserRepository;
import junit.framework.Assert;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegistrarLoginTest {
	private WebDriver chromeAna;
	private WebDriver chromeLucas;
	private WebDriver chromePepe;

	@Autowired
	UserRepository usersRepo;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\CLASE\\Desktop\\TSW\\chromedriver.exe");
	}

	@Test
	public void A_registrarLoginPepe() {

		if (usersRepo.findByName("PepeSelenium").isPresent()) {
			usersRepo.deleteById(usersRepo.findByName("PepeSelenium").get().getId());
		}

		chromePepe = new ChromeDriver();

		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromePepe.get("https://localhost:7500/?ojr=register");

		chromePepe.findElement(By.id("details-button")).click();
		chromePepe.findElement(By.id("proceed-link")).click();
		chromePepe.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromePepe
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));
		WebElement botonCrearCuenta = chromePepe.findElement(By.id("btnCrearCuenta"));

		cajaNombre.sendKeys("PepeSelenium");
		cajaEmail.sendKeys("PepeSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");

		botonCrearCuenta.click();

		new WebDriverWait(chromePepe, 10).ignoring(NoAlertPresentException.class)
				.until(ExpectedConditions.alertIsPresent());

		assertThat(chromePepe.switchTo().alert().getText(), is("Registrado correctamente"));

		chromePepe.switchTo().alert().accept();
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		WebElement loginNombre = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("PepeSelenium");
		loginPwd.sendKeys("123");

		btnEntrar.click();
		
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		WebElement titulo = chromePepe.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
		
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		assertThat(titulo.getText(), is("Fantastico videochat"));

		chromePepe.quit();
	}

	@Test
	public void B_registrarLoginAna() {

		if (usersRepo.findByName("AnaSelenium").isPresent()) {
			usersRepo.deleteById(usersRepo.findByName("AnaSelenium").get().getId());
		}

		chromeAna = new ChromeDriver();

		chromeAna.get("https://localhost:7500/?ojr=register");

		chromeAna.findElement(By.id("details-button")).click();
		chromeAna.findElement(By.id("proceed-link")).click();
		chromeAna.manage().window().setSize(new Dimension(939, 1025));
		
		
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		
		WebElement cajaNombre = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromeAna
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));
		WebElement botonCrearCuenta = chromeAna.findElement(By.id("btnCrearCuenta"));

		cajaNombre.sendKeys("AnaSelenium");
		cajaEmail.sendKeys("AnaSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");

		botonCrearCuenta.click();

		new WebDriverWait(chromeAna, 10).ignoring(NoAlertPresentException.class)
				.until(ExpectedConditions.alertIsPresent());

		assertThat(chromeAna.switchTo().alert().getText(), is("Registrado correctamente"));

		chromeAna.switchTo().alert().accept();
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		WebElement loginNombre = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("AnaSelenium");
		loginPwd.sendKeys("123");

		btnEntrar.click();
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement titulo = chromeAna.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));
		
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		assertThat(titulo.getText(), is("Fantastico videochat"));
		chromeAna.quit();
	}

	@Test
	public void C_registrarLoginLucas() {

		if (usersRepo.findByName("LucasSelenium").isPresent()) {
			usersRepo.deleteById(usersRepo.findByName("LucasSelenium").get().getId());
		}

		chromeLucas = new ChromeDriver();

		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeLucas.get("https://localhost:7500/?ojr=register");

		chromeLucas.findElement(By.id("details-button")).click();
		chromeLucas.findElement(By.id("proceed-link")).click();
		chromeLucas.manage().window().setSize(new Dimension(939, 1025));

		WebElement cajaNombre = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[1]"));
		WebElement cajaEmail = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[2]"));
		WebElement cajaPwd1 = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[3]"));
		WebElement cajaPwd2 = chromeLucas
				.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/input[4]"));
		WebElement botonCrearCuenta = chromeLucas.findElement(By.id("btnCrearCuenta"));

		cajaNombre.sendKeys("LucasSelenium");
		cajaEmail.sendKeys("LucasSelenium@gmail.com");
		cajaPwd1.sendKeys("123");
		cajaPwd2.sendKeys("123");

		botonCrearCuenta.click();

		new WebDriverWait(chromeLucas, 10).ignoring(NoAlertPresentException.class)
				.until(ExpectedConditions.alertIsPresent());

		assertThat(chromeLucas.switchTo().alert().getText(), is("Registrado correctamente"));

		chromeLucas.switchTo().alert().accept();
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement loginNombre = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwd = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrar = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombre.clear();
		loginPwd.clear();

		loginNombre.sendKeys("LucasSelenium");
		loginPwd.sendKeys("123");

		btnEntrar.click();
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		WebElement titulo = chromeLucas.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/h1"));

		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		assertThat(titulo.getText(), is("Fantastico videochat"));
		chromeLucas.quit();
	}

	@Test
	public void D_videollamadas() {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
		options.addArguments("--use-fake-device-for-media-stream");

		// PEPE SE LOGUEA

		chromePepe = new ChromeDriver(options);
		chromePepe.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromePepe.get("https://localhost:7500");
		chromePepe.findElement(By.id("details-button")).click();
		chromePepe.findElement(By.id("proceed-link")).click();
		chromePepe.manage().window().setSize(new Dimension(939, 1025));

		WebElement loginNombrePepe = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwdPepe = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrarPepe = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombrePepe.clear();
		loginPwdPepe.clear();
		loginNombrePepe.sendKeys("PepeSelenium");
		loginPwdPepe.sendKeys("123");
		btnEntrarPepe.click();

		// ANA SE LOGUEA

		chromeAna = new ChromeDriver(options);
		chromeAna.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeAna.get("https://localhost:7500");
		chromeAna.findElement(By.id("details-button")).click();
		chromeAna.findElement(By.id("proceed-link")).click();
		chromeAna.manage().window().setSize(new Dimension(939, 1025));

		WebElement loginNombreAna = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwdAna = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrarAna = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombreAna.clear();
		loginPwdAna.clear();
		loginNombreAna.sendKeys("AnaSelenium");
		loginPwdAna.sendKeys("123");
		btnEntrarAna.click();
		
		// LUCAS SE LOGUEA

		chromeLucas = new ChromeDriver(options);
		chromeLucas.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		chromeLucas.get("https://localhost:7500");
		chromeLucas.findElement(By.id("details-button")).click();
		chromeLucas.findElement(By.id("proceed-link")).click();
		chromeLucas.manage().window().setSize(new Dimension(939, 1025));

		WebElement loginNombreLucas = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[1]/input"));
		WebElement loginPwdLucas = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/input"));
		WebElement btnEntrarLucas = chromeLucas.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[3]/button"));

		loginNombreLucas.clear();
		loginPwdLucas.clear();
		loginNombreLucas.sendKeys("LucasSelenium");
		loginPwdLucas.sendKeys("123");
		btnEntrarLucas.click();		
		
		// PEPE LLAMA A ANA

		// indice de ultimo div determina posicion del usuario, ana es la segunda
		WebElement llamarAna = chromePepe.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div[2]/div[1]/div[2]/button"));
		llamarAna.click();

		// ANA RECHAZA A PEPE
			
		new WebDriverWait(chromeAna, 10).ignoring(NoAlertPresentException.class)
		.until(ExpectedConditions.alertIsPresent());
		
		assertThat(chromeAna.switchTo().alert().getText(), is("Te llama PepeSelenium. ¿Contestar?\n"));
		chromeAna.switchTo().alert().dismiss();
		
		new WebDriverWait(chromePepe, 10).ignoring(NoAlertPresentException.class)
		.until(ExpectedConditions.alertIsPresent());
		
    	assertThat(chromePepe.switchTo().alert().getText(), is("AnaSelenium ha rechazado la llamada"));
		chromePepe.switchTo().alert().accept();
		
		// ANA LLAMA A LUCAS
		
		WebElement llamarLucas = chromeAna.findElement(
				By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div[2]/div[1]/div[3]/button"));
		llamarLucas.click();
		
		// LUCAS ACEPTA
		
		new WebDriverWait(chromeLucas, 10).ignoring(NoAlertPresentException.class)
		.until(ExpectedConditions.alertIsPresent());
		
		assertThat(chromeLucas.switchTo().alert().getText(), is("Te llama AnaSelenium. ¿Contestar?\n"));
		chromeLucas.switchTo().alert().accept();
		
		// COMPROBAR VIDEOLLAMADA
		
		chromeLucas.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		chromeAna.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		WebElement videoAna = chromeAna.findElement(By.xpath("//*[@id=\"widgetVideoLocal\"]"));
		WebElement videoLucas = chromeAna.findElement(By.xpath("//*[@id=\"widgetVideoRemoto\"]"));
		chromeLucas.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		chromeAna.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
//		if(videoAna.isEnabled() && videoLucas.isEnabled()) {
//			chromeAna.quit();
//			chromeLucas.quit();
//			chromePepe.quit();
//		}

		assertThat(videoAna.isEnabled(), is(true));
		assertThat(videoLucas.isEnabled(), is(true));

	}

	@After
	public void tearDown() {
		// chrome.quit();
	}

}